#!/usr/bin/perl

if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help')
{
help();
exit;
}
sub help {
    print "\nFix the number of atoms for a  xyz or pxyz file.\n";
    print "Usage: xyz_fix_lineno  [file.xyz] \n\n";
}


$i=0;
$_=<>;
$comment=<>;

while(<>)
{

$i++;
$buf.=$_;

}

print $i."\n";
print "$comment";
print $buf;

