#!/usr/bin/perl
$bnk="    ";
$molecule=$ARGV[0];shift;$section=$ARGV[0];shift;
$pamln=$ARGV[0];shift;$pamcol=$ARGV[0];shift;$inputpam=$ARGV[0];shift;
$topfile=$ARGV[0];

open (TOP,$topfile);
while(<TOP>)
{
  print;
  $_ =~ s/^\s+//g;
  if ((substr $_, 0, 1) eq ";") {next;}

  if (/moleculetype/i) { #find a molecule type
    while(<TOP>) {
      print;
      $_ =~ s/^\s+//g;
      if ((substr $_, 0, 1) eq ";") {next;}
      chomp;
      ($mol,$nrexc)=split;

      if ($mol =~ /$molecule/i) { #match the molecule tyep
        while(<TOP>) {
          print;
          $_ =~ s/^\s+//g;
          if ((substr $_, 0, 1) eq ";") {next;}

          if (/$section/i) {
            for ($i=0;$i<$pamln;$i++) {
              $_=<TOP>;
              $_ =~ s/^\s+//g;
              if ((substr $_, 0, 1) eq ";") {print;$i--; next; }
              elsif ((substr $_, 0, 1) eq "\[") {die "No line number [ $pamln ] is found in $molecule.[ $section ] !"}                          
#elsif ( /^\s*$|\[/ ) {die "No line number [ $pamln ] is found in $molecule.[ $section ] !"} 
              else { print  unless ($i == $pamln -1); }
            }
            chomp;
            @output=split;
            $output[$pamcol-1]=$inputpam;
            $buf=$output[0];
            for ($i=1;$i<@output;$i++) { $buf=$buf.$bnk.$output[$i]; }
            print $buf."\n";
            last; #exit the section loop
          } else {
            die "No $section is found in $molecule!" if /moleculetype/;
          }

        }
      } 
      else { last; } #exit the molecule loop 
   } 

  }

} #end  loop
