#!/usr/bin/perl
#$dftd3bin="/storage/zhma/razor-scratch/zhma/PROJECT3/PQS_newSettings/templates/fit_D3_functionGroup/dftd3";
#$dftd3bin="/scr/zhma/pqs_new/templates/fit_D3_functionGroup/dftd3";
$dftd3bin="dftd3";
$func=$ARGV[0];shift;

$_=`head -1 $ARGV[0]`;
($num,$emp) = split;
die "are you using standard xyz file rather than pqs xyz file.\n" if $emp;

$outputname="$ARGV[0].eng";
$gradientfile="$ARGV[0].grad";
system("$dftd3bin $ARGV[0] -func $func -bj -grad -old> $outputname"); 
system("mv dftd3_gradient $ARGV[0].d3grad");

