#!/usr/bin/perl
if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help')
{
help();
exit;
}
sub help {
  print "\nExtract gradients from a GAMESS output file.\n";
  print "Usage:  gms_extract_grad  gamess_out \n\n";
}


$bnk='       ';
while(<>)
{
   if(/TOTAL NUMBER OF ATOMS/){chomp; $natms=(split)[5];}
   if(/UNITS ARE HARTREE/){
    for($i=0;$i<$natms;$i++){
      $_=<>;chomp;($ind,$nam,$gx,$gy,$gz)=split;
      print $gx.$bnk.$gy.$bnk.$gz."\n";
    }
  }
}

