#!/usr/bin/perl
if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help')
{
help();
exit;
}
sub help {
  print "\nExtract forces from a PQS output file.\n";
  print "Usage: pqs_extract_frc PQS_out\n\n";
}

print "Gradient from pqs.out{\n";
while(<>)
{
if (/force-x/)
{$_=<>;
while(<>) {
 print substr $_,10 unless (/Sum/);
 last if (/Sum/);
}
}
}

print "} end.\n";


