#!/usr/bin/perl
if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help')
{
help();
exit;
}
sub help {
  print "\nExtract atomic positions from a PQS output file.\n";
  print "Usage: pqs_extract_xyz  PQS_out\n\n";
}

while(<>)
{
if (/Coordinates/)
{$_=<>;$_=<>;$_=<>;
while(<>) {
 print substr $_,6 unless (/Point/);
 last if (/Point/);
}
}
}




