#!/usr/bin/perl
if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help')
{
help();
exit;
}
sub help {
  print "\nAdd the GAMESS gradients to a ref file.\n";
  print "Usage: ref_upd_gms_grad  gamess_grad  [file.ref] \n\n";
}

$conv=-627.5095/0.5291772083;
$bnk="     ";

open(gmslog,"$ARGV[0]") || die "can not open $ARGV[0]\n";shift;
#take tempref file as <>;

$i=0;
while(<gmslog>){
($gxx[$i],$gyy[$i],$gzz[$i]) = split;
$i++;
}

$_=<>;print;
$_=<>;print;
$i=0;
while(<>)
{
($nam,$xxx,$yyy,$zzz, $frx, $fry, $frz, $solv, $molnam)=split;
unless (($nam eq "NetF") | ($nam eq "Torq")){

print $nam.$bnk.$xxx.$bnk.$yyy.$bnk.$zzz.$bnk;
printf "%12.7f$bnk%12.7f$bnk%12.7f",$frx+$gxx[$i]*$conv,$fry+$gyy[$i]*$conv,$frz+$gzz[$i]*$conv;
print $bnk.$solv.$bnk.$molind.$molnam."\n";

$i++;
}
else { print;}

}



