#!/usr/bin/perl
if( $ARGV[0] eq '-h' || $ARGV[0] eq '-help')
{
help();
exit;
}
sub help {
  print "\nAdd the D3 gradients to a ref file.\n";
  print "Usage: ref_upd_d3_grad  d3_grad  [file.ref] \n\n";
}

$conv=-627.5095/0.529177;
$bnk="     ";

open(PQSG,"$ARGV[0]") || die "can not open $ARGV[0]\n";
shift;

#$_=<PQSG>;

$i=0;
while(<PQSG>){
($fxx[$i],$fyy[$i],$fzz[$i]) = split;
$i++;
}

$_=<>;print;
$_=<>;print;
$i=0;
while(<>)
{
($nam,$xxx,$yyy,$zzz, $frx, $fry, $frz, $solv, $molnam)=split;
unless (($nam eq "NetF") | ($nam eq "Torq")){

print $nam.$bnk.$xxx.$bnk.$yyy.$bnk.$zzz.$bnk;
printf "%12.7f$bnk%12.7f$bnk%12.7f",$frx+$fxx[$i]*$conv,$fry+$fyy[$i]*$conv,$frz+$fzz[$i]*$conv;
print $bnk.$solv.$bnk.$molind.$molnam."\n";

$i++;
}
else { print;}

}



